[package]
name = "imgui-ext"
version = "0.1.8"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"
description = "A crate to build debug UIs on structs using a derive macro (based on the imgui crate)"
repository = "https://github.com/germangb/imgui-ext"
readme = "README.md"
keywords = ["gui", "imgui", "macro"]
categories = ["gui", "api-bindings", "game-engines"]
license = "MIT"
exclude = ["ci/*", "page_deploy/*"]

[badges]
travis-ci = { repository = "germangb/imgui-ext", branch = "master" }

[workspace]
members = ["imgui_derive", "example"]

[dependencies]
imgui = "0.0.22"
imgui-ext-derive = { version = "0.1.8", path = "imgui_derive" }

[patch.crates-io]
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2.git" }
